# CatBoost Regression configuration

model_name: "catboost"
model_type: "tree"

# Whether to apply feature selection for this model
apply_feature_selection: false

# Model parameters
parameters:
  iterations: 500
  learning_rate: 0.05
  depth: 8
  l2_leaf_reg: 3.0
  loss_function: "RMSE"
  eval_metric: "RMSE"
  random_strength: 1.0
  bagging_temperature: 0.5  # Some randomness
  border_count: 128  # Default, good for numerical features
  grow_policy: "SymmetricTree"
  bootstrap_type: "Bernoulli"  # Good for large datasets
  subsample: 0.8
  od_type: "Iter"
  od_wait: 100
  random_seed: 42
  verbose: false
  thread_count: -1
  use_best_model: true

# Early stopping
early_stopping:
  enabled: true
  rounds: 100
  metric: "RMSE"

# Hyperparameter tuning
hyperparameter_tuning:
  enabled: true
  method: "optuna"
  n_trials: 40
  cv_folds: 3
  scoring: "neg_mean_squared_error"
  param_space:
    iterations: [300, 1000]
    depth: [6, 10]
    learning_rate: [0.01, 0.1]
    l2_leaf_reg: [1, 10]
    random_strength: [0.5, 2.0]
    bagging_temperature: [0, 1.0]
    subsample: [0.7, 0.9]