# ElasticNet Regression configuration

model_name: "elasticnet"
model_type: "linear"

# Whether to apply feature selection for this model
apply_feature_selection: true

# Model parameters
parameters:
  alpha: 1.0
  l1_ratio: 0.7  # More L1 for feature selection
  fit_intercept: true
  max_iter: 2000
  tol: 0.001
  selection: "cyclic"
  warm_start: false
  random_state: 42

# Hyperparameter tuning
hyperparameter_tuning:
  enabled: true
  method: "optuna"
  n_trials: 40
  cv_folds: 3
  scoring: "neg_mean_squared_error"
  param_space:
    alpha: [0.01, 50.0]  # More focused range
    l1_ratio: [0.5, 0.99]  # Focus on sparse solutions
    selection: ["cyclic", "random"]
    tol: [0.0001, 0.001]