# Ensemble Model configuration

model_name: "ensemble"
model_type: "ensemble"

# Ensemble method
method: "stacking"  # Options: "voting", "stacking", "blending"

# Base models to include in ensemble
base_models:  # Will select best performing models dynamically
  - "ridge"
  - "elasticnet"
  - "random_forest"
  - "xgboost"
  - "lightgbm"
  - "catboost"
  - "sparse_nn"
  - "tabnet"
  # - "saint"  # Uncomment if SAINT is trained

# Voting ensemble parameters
voting:
  weights: "auto"  # Options: "auto", "uniform", or list of weights
  optimize_weights: true  # Use optimization to find best weights
  optimization_method: "differential_evolution"  # Better than grid search

# Stacking ensemble parameters
stacking:
  meta_model: "ridge"  # Options: "ridge", "elasticnet", "xgboost", "linear"
  use_probabilities: false  # For classification only
  cv_folds: 5
  passthrough: false  # Don't include original features in meta-model
  use_oof_predictions: true  # Use out-of-fold predictions for better generalization
  meta_model_params:
    alpha: 1.0
    fit_intercept: true
    solver: "lsqr"  # Good for large datasets

# Blending ensemble parameters
blending:
  blend_size: 0.15  # Proportion of training data for blending (smaller with lots of data)
  meta_model: "ridge"
  meta_model_params:
    alpha: 1.0

# Model selection criteria
model_selection:
  metric: "validation_rmse"  # Metric to use for selecting models
  top_k: 6  # Number of top models to include
  diversity_threshold: 0.5  # Correlation threshold for model diversity
  min_performance: 0.5  # Minimum R2 score to include model
  correlation_threshold: 0.9  # Remove models with highly correlated predictions

# Ensemble optimization
optimization:
  method: "bayesian"  # Options: "grid", "bayesian", "differential_evolution"
  n_iter: 30
  scoring: "neg_mean_squared_error"
  cv_folds: 3

# Advanced options
advanced:
  use_oof_predictions: true  # Use out-of-fold predictions for stacking
  calibrate_predictions: false  # Calibration for probability predictions (classification)
  ensemble_selection: true  # Greedy ensemble selection
  max_ensemble_size: 8  # Maximum number of models in ensemble
  model_weights_constraint: "simplex"  # Ensure weights sum to 1
  min_weight: 0.05  # Minimum 5% weight per model to ensure contribution