# Random Forest Regression configuration

model_name: "random_forest"
model_type: "tree"

# Whether to apply feature selection for this model
apply_feature_selection: false

# Model parameters
parameters:
  n_estimators: 200  # Good starting point
  max_depth: 20  # Prevent overfitting
  min_samples_split: 100  # Higher for 200k samples
  min_samples_leaf: 50  # Higher for stability
  max_features: "sqrt"
  bootstrap: true
  oob_score: true  # Free validation metric
  n_jobs: -1
  random_state: 42
  max_samples: 0.8  # Subsample for speed

# Hyperparameter tuning
hyperparameter_tuning:
  enabled: true
  method: "optuna"
  n_trials: 25
  cv_folds: 3
  scoring: "neg_mean_squared_error"
  param_space:
    n_estimators: [100, 500]
    max_depth: [10, 30]
    min_samples_split: [50, 200]
    min_samples_leaf: [20, 100]
    max_features: ["sqrt", "log2", 0.3]
    max_samples: [0.6, 1.0]