# Random Forest Regression configuration

model_name: "random_forest"
model_type: "tree"

# Whether to apply feature selection for this model
apply_feature_selection: false  # Random Forest has built-in feature selection

# Model parameters
parameters:
  n_estimators: 100
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: "sqrt"  # Options: "sqrt", "log2", float, int, null
  bootstrap: true
  oob_score: false
  n_jobs: -1
  random_state: 42
  verbose: 0

# Hyperparameter tuning
hyperparameter_tuning:
  enabled: true
  method: "random_search"
  n_iter: 30
  cv_folds: 5
  scoring: "neg_mean_squared_error"
  param_distributions:
    n_estimators: [50, 100, 200, 300, 500]
    max_depth: [10, 20, 30, 50, null]
    min_samples_split: [2, 5, 10, 20]
    min_samples_leaf: [1, 2, 4, 8]
    max_features: ["sqrt", "log2", 0.3, 0.5, 0.7]
    bootstrap: [true, false]