# Ridge Regression configuration

model_name: "ridge"
model_type: "linear"

# Whether to apply feature selection for this model
apply_feature_selection: true  # Beneficial for linear models

# Model parameters
parameters:
  alpha: 10.0  # Start with moderate regularization
  fit_intercept: true
  max_iter: 2000  # Increased for convergence
  solver: "saga"  # Good for large datasets
  random_state: 42
  tol: 0.001  # Balance speed vs accuracy

# Hyperparameter tuning
hyperparameter_tuning:
  enabled: true
  method: "optuna"  # Better than grid search for continuous params
  n_trials: 30
  cv_folds: 3  # Fewer folds for speed with large data
  scoring: "neg_mean_squared_error"
  param_space:
    alpha: [0.01, 100.0]  # Narrower, more realistic range
    solver: ["saga", "lsqr"]  # Best for large datasets
    fit_intercept: [true]
    tol: [0.0001, 0.01]