# Ridge Regression configuration

model_name: "ridge"
model_type: "linear"

# Whether to apply feature selection for this model
apply_feature_selection: true

# Model parameters
parameters:
  alpha: 1.0
  fit_intercept: true
  max_iter: 1000
  solver: "auto"  # Options: "auto", "svd", "cholesky", "lsqr", "sparse_cg", "sag", "saga"
  random_state: 42

# Hyperparameter tuning
hyperparameter_tuning:
  enabled: true
  method: "grid_search"  # Options: "grid_search", "random_search", "optuna"
  cv_folds: 5
  scoring: "neg_mean_squared_error"
  param_grid:
    alpha: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]
    solver: ["auto", "svd", "cholesky", "lsqr"]
    fit_intercept: [true, false]