# Main configuration file for  ML pipeline

# Data configuration
data:
  features_path: "data/df_X.csv"
  targets_path: "data/df_Y.csv"
  feature_types_path: "data/feature_types.pkl"  # Dictionary with feature names as keys, "0" or "1" as values
  test_size: 0.2
  random_state: 42

# Preprocessing configuration
preprocessing:
  method: "feature_aware"  # Options: "feature_aware", "standard", "none"
  scaler_additive: "standard"  # Options: "standard", "robust", "minmax"
  scaler_multiplicative: "log"  # Options: "log", "minmax", "none"
  handle_outliers: false
  outlier_threshold: 3  # Standard deviations for outlier detection

# Feature selection configuration
feature_selection:
  method: "auto"  # Options: "smart_pca", "tree_based", "none", "auto"
  pca_variance_threshold: 0.95
  tree_based_top_k: 100
  tree_based_estimator: "random_forest"  # Options: "random_forest", "xgboost"

# Model training configuration
training:
  cv_folds: 5
  validation_strategy: "kfold"  # Options: "kfold", "timeseries", "holdout"
  early_stopping_rounds: 50  # For gradient boosting models
  verbose: true

# Evaluation configuration
evaluation:
  primary_metric: "rmse"  # Options: "rmse", "mae", "r2", "mape", "mse"
  secondary_metrics:
    - "mae"
    - "r2"
    - "mape"
  calculate_feature_importance: true
  save_predictions: true

# Models to run
models_to_run:
  - "ridge"
  - "elasticnet"
  - "random_forest"
  - "xgboost"
  - "lightgbm"
  - "catboost"
  - "sparse_nn"
  - "tabnet"
  # - "saint"  # Uncomment if needed
  # - "ensemble"  # Run after individual models

# Output configuration
output:
  results_dir: "results"
  model_artifacts_dir: "results/model_artifacts"
  feature_importance_dir: "results/feature_importance"
  predictions_dir: "results/predictions"
  plots_dir: "results/plots"
  comparison_file: "results/model_comparison.csv"

# Logging configuration
logging:
  level: "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR"
  log_file: "logs/pipeline.log"

# Computational resources
resources:
  n_jobs: -1  # Number of parallel jobs (-1 for all cores)
  gpu_enabled: false  # Set to true if GPU is available for neural models
  seed: 42